<p>
    Check out the latest versions of Vulnero on GitHub or fork your own.
</p>
<p>
    <a href="<?php echo $this->zipUrl; ?>" title="Download Vulnero <?php echo $this->version; ?>" class="btn info">Download</a>
    <a href="<?php echo $this->githubUrl; ?>" title="GitHub Project Homepage" class="btn">View on GitHub</a>
</p>
<p>
    View the <strong><?php echo $this->version; ?></strong> version <a href="/documentation">documentation</a>.
</p>
