<p>
    <label for="title">Title</label>
    <input class="widefat" id="title" name="title" type="text" value="<?php echo $this->escape(isset($this->settings['title']) ? $this->settings['title'] : ''); ?>" />
</p>
<p>
    <label for="git-user">Git User</label>
    <input class="widefat" id="git-user" name="git-user" type="text" value="<?php echo $this->escape(isset($this->settings['git-user']) ? $this->settings['git-user'] : ''); ?>" />
</p>
<p>
    <label for="git-project">Git Project</label>
    <input class="widefat" id="git-project" name="git-project" type="text" value="<?php echo $this->escape(isset($this->settings['git-project']) ? $this->settings['git-project'] : ''); ?>" />
</p>
